# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch
import random
tensor_A = torch.rand(7,7)
tensor_A

# Create random tensor


tensor([[0.7184, 0.0485, 0.2297, 0.0913, 0.8909, 0.7684, 0.1062],
        [0.8915, 0.3982, 0.8966, 0.7114, 0.5407, 0.6926, 0.1711],
        [0.9515, 0.5359, 0.8051, 0.5847, 0.9783, 0.5321, 0.0515],
        [0.0805, 0.5115, 0.3890, 0.5089, 0.7316, 0.9236, 0.7652],
        [0.5734, 0.3593, 0.7882, 0.7361, 0.9008, 0.8835, 0.2355],
        [0.0736, 0.3102, 0.1299, 0.2731, 0.5092, 0.2746, 0.7549],
        [0.4407, 0.0630, 0.0834, 0.8743, 0.3555, 0.4116, 0.3368]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [8]:
# Create another random tensor
tensor_B = torch.rand(1,7)

# Perform matrix multiplication
matrix_mul = torch.matmul(tensor_A, tensor_B.T)
matrix_mul


tensor([[1.2195],
        [1.8426],
        [1.8975],
        [1.6654],
        [1.7530],
        [1.2148],
        [1.2167]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [22]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(7,7)

# torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(1,7)

# Matrix multiply tensors
random_seed_matrix_mul = torch.matmul(tensor_C, tensor_D.T)
random_seed_matrix_mul, random_seed_matrix_mul.shape



(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [27]:
# Set random seed on the GPU
device = torch.cuda.is_available()
if torch.cuda.is_available():
  RANDOM_SEED = 1234

device


True


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [42]:
# Set random seed

RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device
# Create two random tensors on GPU
tensor_E = torch.rand(2,3)
tensor_F = torch.rand(2,3)

print(tensor_E, device)
print(tensor_F, device)



tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) cuda
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]) cuda



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B



### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
